// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuhmetycfnrxmpwwsfoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1aG1ldHljZm5yeG1wd3dzZm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODc0OTIsImV4cCI6MjA3Mzk2MzQ5Mn0.9Q0RAzadzVknrPG4mc6ETOq7q8YvCgF6pIyR-pDtBlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});